# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[1.14,)" # Require at least 1.14.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="pay_ging"
version="${file.jarVersion}"
displayName="Pay Ging Forge - Kotlin ver."
credits="Thanks for Pay for being Ging"
authors="Dezilaicosed"
description='''
Another inside joke mod, made with Kotlin for Forge
'''
[[dependencies.pay_ging]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pay_ging]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
